/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface PrivateKey {
  privateKeyPem: string
  keyId: string
}
export interface Request {
  url: string
  method: string
  headers: Record<string, string>
}
export interface SignedRequest {
  request: Request
  signingString: string
  signature: string
  signatureHeader: string
}
export declare function createSignedPost(key: PrivateKey, url: string, body: string, additionalHeaders: Record<string, string>): SignedRequest
export declare function createSignedGet(key: PrivateKey, url: string, additionalHeaders: Record<string, string>): SignedRequest
